name       : zita-resampler
version    : 1.6.2
release    : 1
source     :
    - https://kokkinizita.linuxaudio.org/linuxaudio/downloads/zita-resampler-1.6.2.tar.bz2 : 233baefee297094514bfc9063e47f848e8138dc7c959d9cd957b36019b98c5d7
license    : GPL-3.0-or-later
component  : programming.library
summary    : zita-resampler is a C++ library for resampling audio signals. It is designed to be used within a real-time processing context, to be fast, and to provide high-quality sample rate conversion.
description: |
    zita-resampler is a C++ library for resampling audio signals. It is designed to be used within a real-time processing context, to be fast, and to provide high-quality sample rate conversion.
libsplit   : no
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    %patch -p1 < $pkgfiles/0001-Patch-out-ldconfig-change-prefix-while-we-are-at-it.patch
build      : |
    %make -C source
install    : |
    %make_install -C source
